# Generated by Django 5.1.3 on 2025-02-14 09:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=tinymce.models.HTMLField(),
        ),
    ]
