# Generated by Django 5.1.3 on 2025-02-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='wilaya',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.wilaya'),
        ),
    ]
