# Generated by Django 5.1.3 on 2025-02-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_options_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='longitude',
        ),
    ]
