# Generated by Django 5.1.3 on 2025-02-15 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_commune_latitude_remove_commune_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='fullname',
            new_name='fullname_ar',
        ),
        migrations.AddField(
            model_name='testimony',
            name='fullname_fr',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
