# Generated by Django 5.1.3 on 2025-02-15 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_fullname_testimony_fullname_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.AddField(
            model_name='testimony',
            name='content_fr',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
