# Generated by Django 5.1.3 on 2025-02-15 19:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_ar',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_fr',
            field=tinymce.models.HTMLField(),
        ),
    ]
