# Generated by Django 5.1.3 on 2025-02-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_wilaya'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='wilaya',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.wilaya', verbose_name='City'),
            preserve_default=False,
        ),
    ]
