# Generated by Django 5.1.3 on 2025-02-16 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_blog_content_ar_alter_blog_content_fr'),
        ('frontend', '0002_remove_order_address_remove_order_city_order_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_location',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10, verbose_name='Shipping Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Algeria', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.wilaya', verbose_name='Wilaya'),
        ),
    ]
